api_key = 'JCKWIBVETNVIDURE'
username = 'stockvision_jza4_user'
password = 'KLTKtI7xLimPYTXIcf0QyTJXQyP0dOdJ'
host_address = 'dpg-cr3u65g8fa8c73dd5270-a.oregon-postgres.render.com'
datbase_name = 'stockvision_jza4'