api_key = 'JCKWIBVETNVIDURE'
username = 'stockvision_user'
password = 'cgsgXzaBYvACHog9iWP147bODqXvW8Zg'
host_address = 'dpg-cp9su5kf7o1s73a6evf0-a.oregon-postgres.render.com'
datbase_name = 'stockvision'
